version: '3.8'
services:
  api:
    build:
      context: .
      args:
        AWS_ACCESS_KEY_ID: $APPLICATIONS_AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $APPLICATIONS_AWS_SECRET_ACCESS_KEY
        FLASK_SECRET_KEY: $APPLICATIONS_FLASK_SECRET_KEY
    image: applications:0.4
    ports:
      - 5000:5000
