version: '3.8'
services:
  api:
    build:
      context: ./backend
    volumes:
      - .:/code
    ports:
      - 5000:5000
    environment: 
      AWS_ACCESS_KEY_ID: $APPLICATIONS_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $APPLICATIONS_AWS_SECRET_ACCESS_KEY
      FLASK_SECRET_KEY: $APPLICATIONS_FLASK_SECRET_KEY
      MONGO_HOST: $MONGO_HOST
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_DATABASE: applications_dev
    command: bash -c "pip3 install ./backend && flask run"
  frontend:
    build:
      context: ./frontend
    volumes: 
      - ./frontend:/code
    ports:
      - 3000:3000
    # https://github.com/facebook/create-react-app/issues/8688#issuecomment-602110747
    stdin_open: true
    command: bash -c "npm install && npm start"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    command: --quiet --logpath=/dev/null
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8000:8081
    environment:  
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
